version: 0.2

phases:
  pre_build:
    commands:
      - aws s3 rm s3://csce412hchibib.me/ --recursive
  build:
    commands:
      - echo "Build started on `date`"
      - mkdir output
      - cp -r app/* output/

artifacts:
  files:
    - '**/*'
  base-directory: output
